import { Theme } from "../config/theme.slint";
import { LineEdit } from "std-widgets.slint";
import { PButton } from "../components/PButton.slint";



export component AuthForm {
    in-out property <string> password_input;
    in-out property <string> password_placeholder;
    in property <bool> is_first_startup; 

    in-out property <string> form_label_1: "Sebox Setup";
    in-out property <string> form_label_2;

    callback login_submitted(string);
    callback password_created(string);

    Rectangle {
        width:300px; 
        height: 300px; 
        background: #19362B;
        border-radius: 5px;

        // Create Password Form
        if (is_first_startup) : VerticalLayout {
            alignment: center;
            spacing: 20px;
            padding: 30px;

            Text {
                text: root.form_label_1;
                color: Theme.text-color-3;
                font-size: 18px;
                font-weight: 600;
                horizontal-alignment: center;
            }

            LineEdit {
                placeholder-text: root.password_placeholder;
                input-type: password;
                horizontal-alignment: center;
                text <=> password_input;

                accepted(text) => {
                    form_label_1 = "Please Wait...";
                    root.password_created(password_input);
                    password_input = "";
                }
            }

            PButton {
                label: "Confirm";
                clicked => { 
                    form_label_1 = "Please Wait...";
                    root.password_created(root.password_input);
                    password_input = "";
                }
            }
        }

        // Login Form
        if (!is_first_startup) : VerticalLayout {
            alignment: center;
            spacing: 20px;
            padding: 30px;

            Text {
                text: root.form_label_2;
                color: Theme.text-color-3;
                font-size: 18px;
                font-weight: 600;
                horizontal-alignment: center;
            }

            LineEdit {
                placeholder-text: root.password_placeholder;
                input-type: password;
                horizontal-alignment: center;
                text <=> password_input;

                accepted(text) => {
                    root.login_submitted(password_input);
                    password_input = "";
                }
            }

            PButton {
                label: "Unlock";
                clicked => { 
                    root.login_submitted(root.password_input);
                    password_input = "";
                }
            }
        }
    }
}