import { Theme } from "../config/theme.slint";
import { LineEdit } from "std-widgets.slint";
import { PButton } from "../components/PButton.slint";


export component LoginPrompt {
    in-out property <string> user_input;
    callback login_submitted(string);

    Rectangle {
        max-width: 400px;
        height: self.preferred-height;
        background: #19362B;
        border-radius: 5px;

        VerticalLayout {
            alignment: center;
            spacing: 20px;
            padding: 30px;

            Text {
                text: "Unlock Sebox";
                color: #FF0000;
                font-size: 18px;
                font-weight: 600;
                horizontal-alignment: center;
            }

            LineEdit {
                width: 200px;
                placeholder-text: "Enter Password";
                input-type: password;
                horizontal-alignment: center;

                text <=> user_input;
                accepted(text) => {
                    root.login_submitted(root.user_input);
                }
            }

            PButton {
                label: "Unlock";
                clicked => { 
                    root.login_submitted(root.user_input);
                }
            }
        }
    }
}