import { ListView } from "std-widgets.slint";
import { ExplorerItem } from "../components/ExplorerItem.slint";
import { ExplorerItem } from "../models.slint";


export component Content inherits Rectangle {
    in property <[ExplorerItem]> explorer_items: [];
    callback view_file(string);
    background: #EEF5EF;

    VerticalLayout {
        padding: 10px;
        spacing: 8px;

        if explorer_items.length > 0 : ListView {
            for item in explorer_items : ExplorerItem {
                name: item.name;
                is_directory: item.is_directory;
                path: item.path;
                extension: item.extension;
                clicked(filepath) => { view_file(filepath); }
            }
        }

        if explorer_items.length == 0 : HorizontalLayout {
            alignment: center;

            VerticalLayout {
                width: 200px; 
                alignment: center;
                cross-axis-alignment: center;
                spacing: 15px;

                Image {
                    source: @image-url("../../assets/icons/plant-icon.svg");
                    width: 140px;
                    height: 140px;
                    colorize: #4a6755;
                }
                
                Text {
                    text: "Empty Locker";
                    color: #4a6755;
                    font-size: 18px;
                    font-weight: 600;
                    horizontal-alignment: center;
                }
            }
        }
    }
}