import { ListView } from "std-widgets.slint";
import { ExplorerItem } from "../components/ExplorerItem.slint";
import { ExplorerItem } from "../models.slint";



export component Content inherits Rectangle {
    in property <[ExplorerItem]> explorer_items: [];
    background: #EEF5EF;

    VerticalLayout {
        padding: 10px;
        
        ListView {
            for item in explorer_items : ExplorerItem {
                name: item.name;
                is_directory: item.is_directory;
            }
        }
    }
}