export component Header inherits Rectangle {
    height: 80px;
    background: #23483A;

    HorizontalLayout {
        padding-left: 20px;
        
        // App Logo
        // Image {
        //     source: @image-url("logo.png");
        // }

        // App Name 
        Text {
            text: "SEBOX";
            color: #EEF5EF;
            font-size: 24px;
            font-weight: 600;
            letter-spacing: 4px;
            vertical-alignment: center;
        }
    }
}