import "../config/fonts/Sansation-Light.ttf";
import "../config/fonts/Sansation-Regular.ttf";
import "../config/fonts/Sansation-Bold.ttf";

export component Header inherits Rectangle {
    background: #23483A;

    HorizontalLayout {
        padding-left: 20px;
        
        // App Logo
        // Image {
        //     source: @image-url("logo.png");
        // }

        // App Name 
        Text {
            text: "SEBOX";
            color: #EEF5EF;
            font-family: "Sansation";
            font-size: 26px;
            font-weight: 1200;
            letter-spacing: 4px;
            vertical-alignment: center;
        }
    }
}