import { PButton } from "../components/PButton.slint";

export component Sidebar inherits Rectangle {
    callback add_files();

    background: #19362B;
    
    VerticalLayout {
        padding: 20px;
        alignment: start;
        PButton {
            label: "Select Files";
            clicked => { add_files(); }
        }
        
        // Just to fill the remaining empty space
        Rectangle { vertical-stretch: 1; }
    }
}