export global Assets {
    // Image relative path are with reference to ui/components/ExplorerItem.slint - thats where these will be loaded from
    out property <image> text-icon: @image-url("../../assets/icons/text-icon.png");
    out property <image> doc-icon: @image-url("../../assets/icons/doc-icon.png");
    out property <image> image-icon: @image-url("../../assets/icons/image-icon.png");
    out property <image> video-icon: @image-url("../../assets/icons/video-icon.png");
    out property <image> archive-icon: @image-url("../../assets/icons/archive-icon.png");
    out property <image> default-icon: @image-url("../../assets/icons/default-icon.png");
}