import { Header } from "layout/Header.slint";
import { Sidebar } from "layout/Sidebar.slint";
import { Content } from "layout/Content.slint";


export component RootWindow inherits Window {
    title: "Sebox Locker";
    min-width: 800px;
    min-height: 500px; 
    background: #EEF5EF;
 
    callback addFiles(); // Your global bridge to C++

    VerticalLayout {
        Header {} 
        HorizontalLayout {
            Sidebar { pwidth: 200px; }
            Content {
                horizontal-stretch: 1;
                vertical-stretch: 1;
                // 3. When Content triggers its callback, trigger the global one
                addFiles => { root.addFiles(); }
            }
        }
    }
}